### ISSUE TITLE
regression_linear tutorial gives wrong result

### ISSUE THREAD

**Issue by dahvid** [logictensornetworks/tutorials#1]
![graph](https://user-images.githubusercontent.com/7153459/98648154-8f0efa00-233e-11eb-9a9e-3c94cc182117.png)
[requirements.txt](https://github.com/logictensornetworks/tutorials/files/5515814/requirements.txt)

**Comment by sbadredd** [comment]
Hello @dahvid 
I have tried to re-run the tutorial and get the usual results.
Could you share your notebook? I will try to have a look.
In the meantime stay tuned, a new version of LTN should be coming this month. The examples have been updated for it, so you can alternatively wait for the newer version.

**Comment by dahvid** [comment]
Hi Thanks,
I reloaded jupyter and everything works fine, probably some state that gets left in the variables when they're re-assigned.  Do you have any documentation, pydoc or anything? The tutorials left me with some gaps about the SDK.  I guess I'll start to read the code now.
Regards,
David

**Comment by sbadredd** [comment]
Hi David,
Can you have a look at this issue: https://github.com/logictensornetworks/logictensornetworks/issues/6 ?
This may be similar, indeed re-assigning constants/variables does bring problems.

There is no doc for this original code. I'd really recommend waiting a couple of weeks.
We are preparing a new version and this one will have doc :)

Regards
Samy
